server:
  port: 8080
spring:
  application:
    name: phonebook-backend
  main:
    banner-mode: off
  sleuth:
    sampler:
      probability: 1.0
    log:
      slf4j:
        whitelisted-mdc-keys: principal
        enabled: true
    baggage-keys: principal
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://phonebook.c0dw7gzhjayu.eu-central-1.rds.amazonaws.com:3306/phonebook}
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:23528861}
    #    tomcat:
    #      test-while-idle: true
    #      validation-query: 1
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        default_schema: ${FLEXCUBE_DB_SCHEMA:phonebook}
    hibernate:
      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 120000
        loggerLevel: full
        decode404: false
  httpclient:
    enabled: false
    disable-ssl-validation: true
  okhttp:
    enabled: true
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      exposure:
        include: info, health
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: false
    info:
      enabled: true

